jenkins:
  systemMessage: "Jenkins Instance"
  securityRealm:
    local:
      allowsSignup: false
      users:
        - id: "admin"
          password: "123456"
  authorizationStrategy:
    globalMatrix:
      permissions:
        - "Overall/Administer:admin"
        - "Overall/Read:authenticated" 

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: github_token
              username: ${{ secrets.GIT_USERNAME }}
              password: ${{ secrets.GIT_CREDS }}
              description: "GitHub token for Jenkins"
          
          - usernamePassword:
              scope: GLOBAL
              id: dockerhub
              username: ${{ secrets.DOCKERHUB_USERNAME }}
              password: ${{ secrets.DOCKERHUB_PASSWORD }}
              description: "DockerHub token for Jenkins"

jobs:
  - file: /var/lib/jenkins/multibranch-pipeline.groovy

unclassified:
  location:
    url: https://jenkins.bhatiayash.me
